#ifndef BINARY_EXPERIMENTAL_INTERNAL_DEFINE_HPP
#define BINARY_EXPERIMENTAL_INTERNAL_DEFINE_HPP

#define BINARY_EXPERIMENTAL_DEFINE_STATIC_LENGTH_METHOD() static constexpr size_t Length()

#define BINARY_EXPERIMENTAL_DEFINE_STATIC_ENCODE_METHOD_WITH_NAME(ARG_OBJECT_TYPE, ARG_METHOD_NAME) static void ARG_METHOD_NAME(Allocator& allocator, const ARG_OBJECT_TYPE& item)
#define BINARY_EXPERIMENTAL_DEFINE_STATIC_ENCODE_METHOD(ARG_OBJECT_TYPE) BINARY_EXPERIMENTAL_DEFINE_STATIC_ENCODE_METHOD_WITH_NAME(ARG_OBJECT_TYPE, Encode)
#define BINARY_EXPERIMENTAL_DEFINE_STATIC_ENCODE_AUTO_METHOD(ARG_OBJECT_TYPE) BINARY_EXPERIMENTAL_DEFINE_STATIC_ENCODE_METHOD_WITH_NAME(ARG_OBJECT_TYPE, EncodeAuto)
#define BINARY_EXPERIMENTAL_DEFINE_STATIC_ENCODE_WITH_LENGTH_PREFIX_METHOD(ARG_OBJECT_TYPE) BINARY_EXPERIMENTAL_DEFINE_STATIC_ENCODE_METHOD_WITH_NAME(ARG_OBJECT_TYPE, EncodeWithLengthPrefix)

#define BINARY_EXPERIMENTAL_DEFINE_STATIC_DECODE_METHOD_WITH_NAME(ARG_OBJECT_TYPE, ARG_METHOD_NAME) static ARG_OBJECT_TYPE ARG_METHOD_NAME(std::span<const std::byte>& span)
#define BINARY_EXPERIMENTAL_DEFINE_STATIC_DECODE_METHOD(ARG_OBJECT_TYPE) static ARG_OBJECT_TYPE Decode(const std::span<const std::byte>& span)
#define BINARY_EXPERIMENTAL_DEFINE_STATIC_DECODE_AUTO_METHOD(ARG_OBJECT_TYPE) BINARY_EXPERIMENTAL_DEFINE_STATIC_DECODE_METHOD_WITH_NAME(ARG_OBJECT_TYPE, DecodeAuto)

#define BINARY_EXPERIMENTAL_FORWARD_STATIC_LENGTH_METHOD() \
    BINARY_EXPERIMENTAL_DEFINE_STATIC_LENGTH_METHOD() {    \
        return ActualConverterType::Length();              \
    }

#define BINARY_EXPERIMENTAL_FORWARD_STATIC_ENCODE_METHOD()        \
    BINARY_EXPERIMENTAL_DEFINE_STATIC_ENCODE_METHOD(ObjectType) { \
        ActualConverterType::Encode(allocator, item);             \
    }

#define BINARY_EXPERIMENTAL_FORWARD_STATIC_ENCODE_AUTO_METHOD()        \
    BINARY_EXPERIMENTAL_DEFINE_STATIC_ENCODE_AUTO_METHOD(ObjectType) { \
        ActualConverterType::EncodeAuto(allocator, item);              \
    }

#define BINARY_EXPERIMENTAL_FORWARD_STATIC_ENCODE_WITH_LENGTH_PREFIX_METHOD()        \
    BINARY_EXPERIMENTAL_DEFINE_STATIC_ENCODE_WITH_LENGTH_PREFIX_METHOD(ObjectType) { \
        ActualConverterType::EncodeWithLengthPrefix(allocator, item);                \
    }

#define BINARY_EXPERIMENTAL_FORWARD_STATIC_DECODE_METHOD()        \
    BINARY_EXPERIMENTAL_DEFINE_STATIC_DECODE_METHOD(ObjectType) { \
        return ActualConverterType::Decode(span);                 \
    }

#define BINARY_EXPERIMENTAL_FORWARD_STATIC_DECODE_AUTO_METHOD()        \
    BINARY_EXPERIMENTAL_DEFINE_STATIC_DECODE_AUTO_METHOD(ObjectType) { \
        return ActualConverterType::DecodeAuto(span);                  \
    }

namespace binary::experimental {
template <typename T>
struct Converter;
}

#endif
