#ifndef BINARY_INTERNAL_DEFINE_HPP
#define BINARY_INTERNAL_DEFINE_HPP

#define BINARY_DEFINE_OVERRIDE_ENCODE_METHOD_WITH_NAME(ARG_OBJECT_TYPE, ARG_METHOD_NAME) void ARG_METHOD_NAME(Allocator& allocator, const ARG_OBJECT_TYPE& item) override
#define BINARY_DEFINE_OVERRIDE_ENCODE_METHOD(ARG_OBJECT_TYPE) BINARY_DEFINE_OVERRIDE_ENCODE_METHOD_WITH_NAME(ARG_OBJECT_TYPE, Encode)
#define BINARY_DEFINE_OVERRIDE_ENCODE_AUTO_METHOD(ARG_OBJECT_TYPE) BINARY_DEFINE_OVERRIDE_ENCODE_METHOD_WITH_NAME(ARG_OBJECT_TYPE, EncodeAuto)
#define BINARY_DEFINE_OVERRIDE_ENCODE_WITH_LENGTH_PREFIX_METHOD(ARG_OBJECT_TYPE) BINARY_DEFINE_OVERRIDE_ENCODE_METHOD_WITH_NAME(ARG_OBJECT_TYPE, EncodeWithLengthPrefix)

#define BINARY_DEFINE_OVERRIDE_DECODE_METHOD_WITH_NAME(ARG_OBJECT_TYPE, ARG_METHOD_NAME) ARG_OBJECT_TYPE ARG_METHOD_NAME(std::span<const std::byte>& span) override
#define BINARY_DEFINE_OVERRIDE_DECODE_METHOD(ARG_OBJECT_TYPE) ARG_OBJECT_TYPE Decode(const std::span<const std::byte>& span) override
#define BINARY_DEFINE_OVERRIDE_DECODE_AUTO_METHOD(ARG_OBJECT_TYPE) BINARY_DEFINE_OVERRIDE_DECODE_METHOD_WITH_NAME(ARG_OBJECT_TYPE, DecodeAuto)
#define BINARY_DEFINE_OVERRIDE_DECODE_WITH_LENGTH_PREFIX_METHOD(ARG_OBJECT_TYPE) BINARY_DEFINE_OVERRIDE_DECODE_METHOD_WITH_NAME(ARG_OBJECT_TYPE, DecodeWithLengthPrefix)

#define BINARY_DISABLE_COPY(ARG_TYPE)   \
    ARG_TYPE(const ARG_TYPE&) = delete; \
    ARG_TYPE& operator=(const ARG_TYPE&) = delete;

#define BINARY_DISABLE_COPY_MOVE(ARG_TYPE) \
    BINARY_DISABLE_COPY(ARG_TYPE)          \
    ARG_TYPE(ARG_TYPE&&) = delete;         \
    ARG_TYPE& operator=(ARG_TYPE&&) = delete;

#endif
