name: benchmark
"on": push
permissions:
  deployments: write
  contents: write
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        run: sh scripts/setup.sh

      - name: Build Benchmarks
        run: sh scripts/build-benchmarks.sh

      - name: Benchmark
        run: sh scripts/run-benchmark-report.sh

      - name: Store Benchmark Result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: "googlecpp"
          output-file-path: "build-result/benchmark-result.json"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
