name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        run: sh scripts/setup.sh

      - name: Build Tests
        run: sh scripts/build-tests.sh

      - name: Coverage
        run: sh scripts/run-coverage.sh

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          fail-on-error: false
          file: "build-result/lcov.info"
